HotelXYZ/urls.py
"""HotelXYZ URL Configuration"""
from django.conf.urls import url
from django.contrib import admin
from hotel.views import RoomView, AddRoomView, reservation

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/', RoomView.as_view(), name="room"),
    url(r'^add/', AddRoomView.as_view(), name="add room"),
    url(r'^reservation/', reservation, name="reservation"),
]

hotel/models.py
from django.db import models


class Room(models.Model):
    STATUS_CHOICES = (
        ('Available', 'Available'),
        ('Busy', 'Busy')
    )
    room_number = models.IntegerField(null=False, primary_key=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='Available')
    guest_name = models.CharField(max_length=25, null=True, blank=True, default=None)

    class Meta:
        ordering = ['room_number']

hotel/forms.py
from django import forms
from hotel.models import Room


class AddRoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = ['room_number']

hotel/views.py
from django.views.generic import ListView, CreateView
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response

from hotel.forms import AddRoomForm
from hotel.models import Room
from hotel.serializers import RoomSerializer


class RoomView(ListView):
    model = Room
    template_name = 'hotel/rooms.html'


class AddRoomView(CreateView):
    form_class = AddRoomForm
    template_name = 'hotel/add_room.html'
    success_url = "/home/"


@api_view(['GET', 'POST'])
def reservation(request, format=None):
    if request.method == 'GET':
        rooms = Room.objects.all()
        serializer = RoomSerializer(rooms, many=True)
        return Response(serializer.data)

    elif request.method == 'POST':
        try:
            serializer = RoomSerializer(data=request.data)
            room_number = serializer.initial_data.get("room_number")
            guest_name = serializer.initial_data.get("guest_name")
            room = Room.objects.get(room_number=room_number)
        except Room.DoesNotExist:
            return Response("This room has not exists",
                            status=status.HTTP_404_NOT_FOUND)

        serializer = RoomSerializer(room, data=request.data)
        if serializer.is_valid():
            room_number = serializer.data.get("room_number")
            room = Room.objects.get(room_number=room_number)
            if room.status == "Available":
                room.status = "Busy"
                room.guest_name = guest_name
                room.save()
            else:
                return Response("This room is busy",
                                status=status.HTTP_400_BAD_REQUEST)
            return Response("Added a new reservation",
                            status=status.HTTP_201_CREATED)
        return Response(serializer.errors,
                        status=status.HTTP_400_BAD_REQUEST)

hotel/templates/hotel/add_room.html
{% extends 'hotel/base.html' %}

{% block content %}

<div class="row">
    <h1>Add room</h1>

    <form method="POST"> {%csrf_token%}
        {{ form.as_p }}
        <button type="submit">Add new room</button>
    </form>
</div>

{% endblock %}

hotel/templates/hotel/base.html
<html>
    <head>
        <style>
div {
    margin: 35px;
}
</style>
        <title>Hotel XYZ</title>

    </head>
<body>

    <div class="page-header">
        <h1>Hotel XYZ</h1>
        <a href="/home/">Rooms</a>
        <a href="/add/">Add</a>
    </div>
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
</body></html>

hotel/templates/hotel/rooms.html
{% extends 'hotel/base.html' %}

{% block content %}
<style>
        table, th, td {
        border: 1px solid black;
        padding: 3px;
        border-collapse: collapse;
        text-align: center;
        }
        h2 {text-align: center;
        }

</style>
<div class="row">
    <h2>Rooms</h2>

    <table style="width:100%">

        <tr>
            <th >Room number</th>
            <th>Status</th>
            <th>Guest name</th>
        </tr>
        {% for obj in room_list %}
        <tr>
            <td>{{obj.room_number}}</td>
            <td> {{obj.status}}</td>
            <td> {{obj.guest_name}}</td>
        </tr>
        {% endfor %}

    </table>
    <button type="submit"><a href="/add/">Add new room</a></button>
</div>

{% endblock %}